import * as React from "react"
import {
    ArrowUpCircleIcon,
    BarChartIcon,
    CalendarClock,
    CameraIcon,
    ClipboardListIcon,
    DatabaseIcon,
    FileCodeIcon,
    FileIcon,
    FileTextIcon,
    FolderIcon,
    HelpCircleIcon,
    LayoutDashboardIcon,
    ListIcon,
    SearchIcon,
    SettingsIcon,
    UsersIcon,
} from "lucide-react"

import { NavDocuments } from "@/Components/nav-documents"
import { NavMain } from "@/Components/nav-main"
import { NavSecondary } from "@/Components/nav-secondary"
import { NavUser } from "@/Components/nav-user"
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from "@/Components/ui/sidebar"
import { usePage } from "@inertiajs/react"

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {

    const { url } = usePage()

    // Create a function to determine if a route is active
    const isRouteActive = (path: string) => {
        // Transform path to handle route() generated URLs
        const currentPath = url.split('?')[0]  // Remove query params

        // For string URLs like 'dashboard', check if the current URL ends with it
        if (typeof path === 'string' && !path.startsWith('http')) {
            return currentPath.endsWith(path)
        }

        // For full URLs generated by route(), extract the last part of the path
        if (typeof path === 'string' && path.startsWith('http')) {
            const pathSegments = path.split('/')
            const currentSegments = currentPath.split('/')
            return pathSegments[pathSegments.length - 1] === currentSegments[currentSegments.length - 1]
        }

        return false
    }



    const data = {
        user: {
            name: "Admin",
            email: "Admin@example.com",
            avatar: "/avatars/shadcn.jpg",
        },
        navMain: [
            {
                title: "Dashboard",
                url: route('dashboard'),
                icon: LayoutDashboardIcon,
                isActive: isRouteActive('dashboard'),
            },
            {
                title: "Employee",
                url: route('employeepanel.employee'),
                icon: ListIcon,
                isActive: isRouteActive('employee'),

            },
            {
                title: "Attendance",
                url: route('attendancepanel.attendance'),
                icon: CalendarClock,
            },
            {
                title: "Tasks",
                url: "#",
                icon: FolderIcon,
            },
            {
                title: "Team",
                url: "#",
                icon: UsersIcon,
            },
        ],

        navSecondary: [
            {
                title: "Settings",
                url: "#",
                icon: SettingsIcon,
            },
            {
                title: "Get Help",
                url: "#",
                icon: HelpCircleIcon,
            },
            {
                title: "Search",
                url: "#",
                icon: SearchIcon,
            },
        ],
        documents: [
            {
                name: "Data Library",
                url: "#",
                icon: DatabaseIcon,
            },
            {
                name: "Reports",
                url: "#",
                icon: ClipboardListIcon,
            },

        ],
    }

    return (
        <Sidebar collapsible="offcanvas" {...props}>
            <SidebarHeader>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <SidebarMenuButton
                            asChild
                            className="data-[slot=sidebar-menu-button]:!p-1.5"
                        >
                            <a href="#">
                                <ArrowUpCircleIcon className="h-5 w-5" />
                                <span className="text-base font-semibold">Acme Inc.</span>
                            </a>
                        </SidebarMenuButton>
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarHeader>
            <SidebarContent>
                <NavMain items={data.navMain} />
                <NavDocuments items={data.documents} />
                <NavSecondary items={data.navSecondary} className="mt-auto" />
            </SidebarContent>
            <SidebarFooter>
                <NavUser user={data.user} />
            </SidebarFooter>
        </Sidebar>
    )
}
